language:
  java

sudo:
  false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install:
  skip

addons:
  sonarcloud:
    organization: "piggyback"

services:
  - docker

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-offers
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t piggy1/offers .
  - docker push piggy1/offers

after_success:
  - bash <(curl -s https://codecov.io/bash)
