language:
  java

sudo:
  false

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install:
  skip

addons:
  sonarcloud:
    organization: "piggyback"

services:
  - docker

script:
  - mvn clean verify sonar:sonar -Dsonar.projectKey=piggy1-mvn_piggyback-offers
  - docker build -t piggy1/offers .

deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master

after_success:
  - bash <(curl -s https://codecov.io/bash)
