apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-offers-canary
  namespace: production
spec:
  replicas: 0
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-offers
        env: canary
    spec:
      containers:
      - image: gcr.io/omega-palace-254907/piggy1-offers:v11
        name: piggyback-prod-runner-offers
        env:
          - name: JASYPT_ENCRYPTOR_PASSWORD
            valueFrom:
              secretKeyRef:
                name: jasypt-password
                key: password
        resources:
          limits:
            memory: "384Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: piggy-offers
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8081
status: {}
