apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: piggyback-offers-production
  namespace: production
spec:
  replicas: 2
  progressDeadlineSeconds: 10
  template:
    metadata:
      labels:
        app: piggyback-offers
        env: production
    spec:
      containers:
      - image: gcr.io/absolute-text-251105/piggy1-offers:v2
        name: piggyback-prod-runner-offers
        resources:
          limits:
            memory: "384Mi"
            cpu: "300m"
        imagePullPolicy: Always
        ports:
        - name: piggy-offers
          containerPort: 8081
        readinessProbe:
          httpGet:
            path: /swagger-ui.html
            port: 8081
status: {}
